/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = async function(knex) {
  // 删除已有数据
  await knex('resumes').del();
  
  // 插入种子数据
  await knex('resumes').insert([
    {
      id: 1,
      user_id: 14, // 对应shipper@test.com用户
      name: '张三',
      position: 'CLASS A 司机',
      experience: '5年经验',
      location: '洛杉矶',
      phone: '(323) 456-7890',
      email: 'zhangsan@example.com',
      skills: JSON.stringify(['CDL-A驾照', '长途运输', '货物装卸', '10年安全驾驶记录']),
      summary: '有5年CLASS A驾驶经验，熟悉加州及西部各州路线，安全驾驶记录良好，责任心强。',
      expected_salary: '$5000-6000/月',
      work_type_preference: '全职',
      views: 15,
      is_active: true,
      is_featured: false,
      created_at: new Date('2025-06-26'),
      updated_at: new Date('2025-06-26')
    },
    {
      id: 2,
      user_id: 14,
      name: '李四',
      position: '仓库主管',
      experience: '8年经验',
      location: '纽约',
      phone: '(212) 567-8901',
      email: 'lisi@example.com',
      skills: JSON.stringify(['仓储管理', 'WMS系统操作', '团队管理', '叉车操作证']),
      summary: '8年仓储物流管理经验，熟练操作各类WMS系统，具备团队管理能力，有丰富的库存控制经验。',
      expected_salary: '$4500-5500/月',
      work_type_preference: '全职',
      views: 22,
      is_active: true,
      is_featured: true,
      created_at: new Date('2025-06-25'),
      updated_at: new Date('2025-06-25')
    },
    {
      id: 3,
      user_id: 14,
      name: '王五',
      position: '货运代理',
      experience: '3年经验',
      location: '旧金山',
      phone: '(415) 678-9012',
      email: 'wangwu@example.com',
      skills: JSON.stringify(['客户开发', '业务谈判', '英语流利', '报关知识']),
      summary: '3年货运代理经验，擅长客户关系维护和业务开发，英语流利，熟悉进出口流程。',
      expected_salary: '$4000-5000/月',
      work_type_preference: '全职',
      views: 8,
      is_active: true,
      is_featured: false,
      created_at: new Date('2025-06-24'),
      updated_at: new Date('2025-06-24')
    },
    {
      id: 4,
      user_id: 14,
      name: '刘六',
      position: 'CLASS B 司机',
      experience: '2年经验',
      location: '芝加哥',
      phone: '(312) 789-0123',
      email: 'liuliu@example.com',
      skills: JSON.stringify(['CDL-B驾照', '本地配送', '货物装卸', '客户服务']),
      summary: '2年CLASS B驾驶经验，主要从事本地配送工作，熟悉芝加哥及周边路线，服务态度良好。',
      expected_salary: '$3500-4500/月',
      work_type_preference: '全职',
      views: 12,
      is_active: true,
      is_featured: false,
      created_at: new Date('2025-06-23'),
      updated_at: new Date('2025-06-23')
    },
    {
      id: 5,
      user_id: 14,
      name: '陈七',
      position: '调度员',
      experience: '4年经验',
      location: '休斯顿',
      phone: '(713) 890-1234',
      email: 'chenqi@example.com',
      skills: JSON.stringify(['车辆调度', '路线规划', '数据分析', '沟通协调']),
      summary: '4年物流调度经验，熟练使用调度软件，擅长路线优化和成本控制，具备良好的沟通协调能力。',
      expected_salary: '$3800-4800/月',
      work_type_preference: '全职',
      views: 18,
      is_active: true,
      is_featured: false,
      created_at: new Date('2025-06-22'),
      updated_at: new Date('2025-06-22')
    },
    {
      id: 6,
      user_id: 14,
      name: '赵八',
      position: '文员OP',
      experience: '1年经验',
      location: '凤凰城',
      phone: '(602) 901-2345',
      email: 'zhaoba@example.com',
      skills: JSON.stringify(['办公软件', '数据录入', '客户服务', '文档管理']),
      summary: '1年办公室文员经验，熟练使用Office软件，工作细心负责，学习能力强。',
      expected_salary: '$2800-3500/月',
      work_type_preference: '全职',
      views: 6,
      is_active: true,
      is_featured: false,
      created_at: new Date('2025-06-21'),
      updated_at: new Date('2025-06-21')
    },
    {
      id: 7,
      user_id: 14,
      name: '孙九',
      position: '跟单员',
      experience: '3年经验',
      location: '费城',
      phone: '(215) 012-3456',
      email: 'sunjiu@example.com',
      skills: JSON.stringify(['订单跟踪', '客户沟通', '问题处理', 'ERP系统']),
      summary: '3年跟单工作经验，熟悉订单流程管理，具备良好的客户沟通能力和问题解决能力。',
      expected_salary: '$3200-4000/月',
      work_type_preference: '全职',
      views: 14,
      is_active: true,
      is_featured: false,
      created_at: new Date('2025-06-20'),
      updated_at: new Date('2025-06-20')
    },
    {
      id: 8,
      user_id: 14,
      name: '周十',
      position: '会计',
      experience: '6年经验',
      location: '圣地亚哥',
      phone: '(619) 123-4567',
      email: 'zhoushi@example.com',
      skills: JSON.stringify(['财务软件', '应收应付', '税务处理', 'QuickBooks']),
      summary: '6年会计工作经验，熟练处理应收应付账款，熟悉美国税务制度，具备CPA资格。',
      expected_salary: '$4200-5200/月',
      work_type_preference: '全职',
      views: 25,
      is_active: true,
      is_featured: true,
      created_at: new Date('2025-06-19'),
      updated_at: new Date('2025-06-19')
    },
    {
      id: 9,
      user_id: 14,
      name: '吴十一',
      position: '卸柜工',
      experience: '1年经验',
      location: '达拉斯',
      phone: '(214) 234-5678',
      email: 'wushiyi@example.com',
      skills: JSON.stringify(['货物装卸', '叉车操作', '体力工作', '团队合作']),
      summary: '1年卸柜工作经验，身体素质好，能够承担重体力劳动，有叉车操作证。',
      expected_salary: '$2500-3200/月',
      work_type_preference: '全职',
      views: 9,
      is_active: true,
      is_featured: false,
      created_at: new Date('2025-06-18'),
      updated_at: new Date('2025-06-18')
    },
    {
      id: 10,
      user_id: 14,
      name: '郑十二',
      position: '销售',
      experience: '5年经验',
      location: '西雅图',
      phone: '(206) 345-6789',
      email: 'zhengshier@example.com',
      skills: JSON.stringify(['客户开发', '销售谈判', '市场分析', '英语流利']),
      summary: '5年物流销售经验，具备丰富的客户资源和销售技巧，英语流利，业绩优秀。',
      expected_salary: '$4000-6000/月 + 提成',
      work_type_preference: '全职',
      views: 31,
      is_active: true,
      is_featured: true,
      created_at: new Date('2025-06-17'),
      updated_at: new Date('2025-06-17')
    }
  ]);
}; 